### ISSUE TITLE
Continue and parallel computation

### ISSUE THREAD

**Issue by w6ye** [rouyang2017/SISSO#16]
Hi Dr.Ouyang,

1. I realized the program would generate a CONTINUE file and there is a flag in the SISSO.in that seems to give us the option to continue calculations after it is interrupted. So to restart the calculation do I simply need to change from false to true for 'restart' flag in the input?

2. For some reason, it takes me the same time using 2 nodes as using 1 node. What would you suggest to run the program most efficiently?

Thanks.

**Comment by rouyang2017** [comment]
1. Yes.

2. I guess that you have small jobs so that 2 nodes take same time with that using 1 node, right?  Nevertheless the code need to be optimized by a computer expert, and this is in progress.

**Comment by w6ye** [comment]
Thanks for your reply.
1. However I always encounter a mpirun error when I try to restart some runs. And I've checked it is not the memory problem. 
2. The job took 4 hours (I only tested using rung = 2),  it took exactly the same time using 2nodes vs 1node.  
3. Have you tested how much a difference rung=2 vs rung=3 would give to the result?  And also the subs_sis? 

Thanks!

**Comment by rouyang2017** [comment]
I need to see your input setting before I can answer your questions. So please send me a email if that is OK. 
rung=2 and rung=3 should give different results since rung=3 corresponds to a big feature space with more complex features. In principle, the larger the subs_sis the higher the probability to identify the best model. So I would use as large subspace as possible unless e.g. I see a convergence.  The 1D is the same no matter what subs_sis was set since the 1D is just the first feature selected by SIS.
