### ISSUE TITLE
How to predict new data manually with classification SISSO

### ISSUE THREAD

**Issue by MarcDuquesnoy** [rouyang2017/SISSO#26]
Dear Dr. Ouyang, 

first of all, thanks a lot for provinding such a very reliable method for regression and classification. That helps me a lot in my works !

I have one question about the classification method. I computed the example from your github and also tried to test with some of my dataset to see if I understandd well the methodology.

Neverthless, after finding descriptors in "SISSO.out", I predict new output manually, not with Fortran since it does not work on my computer (I really don't know why I face issues for predicting). For the regression I do excatly the same but it is more simple since it is a regression equation.

Thus, about the SVM approaches you mentionned on this github : 
    - Is it possible to use SISSO to find a subpsace where you project the initial dataset, and then use a SVM approach to construct a classifier on SISSO descriptors ?

Otherwise, is it possible to predict manually (I mean with somethings I could forget in the SISSO folder) new data points without using fortran ?

Thanks a lot for your time.

Marc

**Comment by rouyang2017** [comment]
Hi Marc,

"- Is it possible to use SISSO to find a subpsace where you project the initial dataset, and then use a SVM approach to construct a classifier on SISSO descriptors ?"
Yes, this is what we did in the work: J. Phys.: Mater. 2, 024002 (2019)

"Otherwise, is it possible to predict manually (I mean with somethings I could forget in the SISSO folder) new data points without using fortran ?"
We can predict new data by looking which convex domain it locates in the map. However, when the new data is outside any of the convex domains, then it is unclear which domain it belongs to, and SVM my help in this case.
