### ISSUE TITLE
Max number of tasks for multi target

### ISSUE THREAD

**Issue by ppdebreuck** [rouyang2017/SISSO#30]
Hi,

Is there any limitation to the maximum number of tasks when doing multi task SISSO?
For instance, I have 160 properties (they are some temperature variable), with 200 samples each. My train.dat file thus contains 32001 lines. In SISSO.in I have ntasks=160 and nsamples=200,200,... 160 times. However, I get an end-of-file during read error. Reducing the ntask parameter to 123 works (124 not) while leaving the rest as it works.

Also if I do exactly the same but for 80 tasks (ntask=80, 16001 lines in train.dat, and 200,200,... 80 times) everything works, so I assume my input files are right.

Thank you.

**Comment by rouyang2017** [comment]
Hi, there is no limitation to the max number of tasks, but the max acceptable line-length in SISSO.in was set to 500 character since users usually only have few numbers to input each line.
In your case, please open the file SISSO.f90, and at line 23 you find the variable declaration of "nsample_line*500". Please replace the 500 by a large value you want and then recompile SISSO. Please let me know if this doesn't solve your problem.

**Comment by ppdebreuck** [comment]
Worked! Also had to change line 333.
Thanks
