### ISSUE TITLE
parallelisation

### ISSUE THREAD

**Issue by vonruti** [rouyang2017/SISSO#4]
Could you please give some suggestions how to run your code? If I use a small amount of CPU'S the code of course gets very slow after a few iterations. However, if I start with a large amount of CPU's the code does not proceed at the very beginning. I figured out that I can start with a small number of CPU's and then restart the code with a larger amount of CPU's one there is no progress visible. But this seems not to be a very elegant solution.

**Comment by rouyang2017** [comment]
Thank you for your question. In general, there is a linear scaling of the  parallelisation efficiency up to many cores, e.g. using several hundreds of cores to finish a job in hours should be within the linear scaling. I don't know how many cores you were using for how large jobs.  The problem "does not proceed at the very beginning" may be caused by two: (1) When you are using many cores, there is some waiting time for parallel initialisation; (2) There is a delay of output to the file SISSO.out, but the code is actually running, and if you check the running log file you will find the progress updating. Please check if these are true for your cases.

**Comment by vonruti** [comment]
Thank you for your answer. Yes it seems that with many cores the program needs several minutes for the first iteration without writing anything down (also not in the log file). I just did not wait long enough.
